"use client";

import { usePathname } from "next/navigation";
import { Command, Info, Search } from "lucide-react";
import { istClock } from "@/lib/clock";
import { setPaletteOpen, useNow } from "@/lib/hooks";
import { cn } from "@/lib/utils";

const TITLES: [RegExp, string, string][] = [
  [/^\/$/, "Market Overview", "Indian index derivatives · live desk"],
  [/^\/chain/, "Option Chain", "Strike-level OI, Greeks and positioning"],
  [/^\/analytics/, "Derivatives Analytics", "OI profiles, PCR, IV structure and build-up"],
  [/^\/strategy/, "Strategy Lab", "Multi-leg payoff, risk and probability"],
  [/^\/research/, "AI Research", "Copilot + auto-generated desk briefs"],
  [/^\/notes/, "Desk Notes", "Research journal and playbooks"],
];

export default function TopBar() {
  const pathname = usePathname();
  const now = useNow(1000);
  const clock = istClock(now);
  const [, title, sub] = TITLES.find(([re]) => re.test(pathname)) ?? TITLES[0];

  return (
    <header className="sticky top-0 z-30 border-b border-line bg-paper/85 backdrop-blur-md">
      <div className="mx-auto flex h-16 max-w-[1440px] items-center gap-4 px-5 lg:px-8">
        <div className="min-w-0">
          <h1 className="text-[15px] font-bold leading-tight tracking-tight">{title}</h1>
          <p className="hidden text-[11px] text-faint sm:block">{sub}</p>
        </div>

        <div className="mx-auto hidden w-full max-w-sm sm:block">
          <button
            onClick={() => setPaletteOpen(true)}
            className="flex h-9 w-full items-center gap-2.5 rounded-lg border border-line2 bg-panel px-3 text-[12.5px] text-faint shadow-card transition-all hover:border-faint hover:text-sub"
          >
            <Search size={14.5} />
            <span className="flex-1 text-left">Search instruments, pages…</span>
            <span className="hidden items-center gap-0.5 rounded border border-line bg-paper px-1.5 py-0.5 text-[10px] font-semibold sm:flex">
              <Command size={10} />K
            </span>
          </button>
        </div>
        <button
          onClick={() => setPaletteOpen(true)}
          className="ml-auto grid h-9 w-9 place-items-center rounded-lg border border-line2 bg-panel text-faint shadow-card transition-colors hover:text-ink sm:hidden"
          aria-label="Search"
        >
          <Search size={15} />
        </button>

        <div className="flex items-center gap-2.5">
          <div
            className="tip hidden cursor-help items-center gap-1.5 rounded-lg border border-line bg-panel px-2.5 py-1.5 md:flex"
            data-tip="All market data is generated by a deterministic intraday simulation for product demonstration."
          >
            <Info size={13} className="text-faint" />
            <span className="text-[10.5px] font-semibold text-faint">SIMULATED</span>
          </div>
          <div className="flex items-center gap-2 rounded-lg border border-line bg-panel px-2.5 py-1.5">
            <span
              className={cn(
                "h-1.5 w-1.5 rounded-full",
                clock.session === "open" ? "bg-up animate-pulse-dot" : clock.session === "preopen" ? "bg-warn animate-pulse-dot" : "bg-faint"
              )}
            />
            <span className="num text-[11.5px] font-semibold tabular-nums">{clock.time}</span>
            <span className="text-[10.5px] font-medium text-faint">IST</span>
          </div>
        </div>
      </div>
    </header>
  );
}
